import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
// import { Header } from "@/components/Header";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.variable}
        suppressHydrationWarning
      >
       {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
